# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: weather

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  region: us-west-2
  runtime: dotnetcore2.0

# you can add packaging information here
package:
  artifact: bin/release/netcoreapp2.0/deploy-package.zip
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**


# Adding the functions
functions:
  weather:
    handler: CsharpHandlers::WeatherService.Handler::Hello

#Setting up the APIGateWay end point
    events:
      - http:
          path: /
          method: get
